### ISSUE TITLE
Kong with external DB in RDS

### ISSUE THREAD

**Issue by maestrofx** [Goomeo/rancher-catalog#1]
Hi @throrin19 ,

OOT,
Have you trying this Kong Rancher catalog using external DB, say in RDS?

Thank you.

**Comment by throrin19** [comment]
Hi @maestrofx 

No, this kong rancher calalog use a stack `postgres` database with a `rancher-nfs` volume driver to save data

**Comment by maestrofx** [comment]
late reply,

I try your repo, it's nice one and updated to latest Kong.
I try with environment variables in compose, it works great too!

Thanks.
